classDiagram
    class PasswordUtils
    class CrittografiaFile
    class InitFileSystem
    class ConfigFile
    class InitFileSystem_backup
    class ScritturaFile
    class CreazioneEliminazioneFile
    class LetturaFile
    class HealingFile
    class ControlloDatiIniziale
    class CostruttorePath
    class ConfigFile_backup
    class AppLauncher
    class ValidatoreDati
    class CreazioneEliminazionePersone
    class Medico
    class Terapia
    class IT
    class Log
    class Esame
    class Persona
    class Amministratore
    class Paziente
    class Segretario
    class Visita
    class ControlloLogin
    class MainClass
    class SchermataLoginUI
    class SchermataAggiungiPazienteUI
    class HomeMedicoUI
    class SchermataHomeItUI
    class ListaPazientiUI
    class SchermataHomeSegretarioUI
    class HomeAmministratoreUI
    class PrimoAvvioUI
    class PrescriviTerapiaController
    class HomeAmministratoreController
    class AggiungiITController
    class GestioneUtentiITcontroller
    class ListaPazientiController
    class AggiungiSegretarioController
    class LoginController
    class AggiungiPazienteController
    class GestioneStaffController
    class EffettuaEsameController
    class AggiungiAmministratoreController
    class ModificaPazienteController
    class HomeMedicoController
    class AggiungiMedicoController
    class DettagliPazienteController
    class EffettuaVisitaController
    class HomeSegretarioController
    class HomeITcontroller
    class PrenotaVisitaController
    class PrimoAvvioController
    class PrenotaEsameController
    class module-info
